spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/androidDev?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: weileqian0819
  main:
    allow-bean-definition-overriding: true
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    #      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQLDialect
#    show-sql: true
#    open-in-view: false
#    database: mysql