spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/androidDev?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: weileqian0819
  main:
    allow-bean-definition-overriding: true